services:
  - type: web
    name: fullstack-fastapi-react
    env: python
    rootDir: backend
    buildCommand: |
      cd ../frontend && npm install && npm run build
      pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
